name: rpo_gene
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bioconda::blast=2.10.
  - conda-forge::parallel=20200522
  - bioconda::bedtools=2.29.2
  - bioconda::seqtk=1.3
  - bioconda::vsearch=2.15.0
  - bioconda::mafft=7.471
  - bioconda::trimal=1.4.1
  - bioconda::raxml=8.2.12
